### ISSUE TITLE
Debugging Problem

### ISSUE THREAD

**Issue by JeromSar** [eishub/Starcraft#58]
Sometimes, during debugging (in particular during stepping), the eclipse editor glitches and does not show the current point of execution, nor allows stepping. Additionally, pausing and resuming execution does not work. The image below hopefully illustrates what I mean:

![eclipse](https://i.gyazo.com/b86a8c9d8e6797c65be9955cb6c15eb3.png)

**Comment by Venorcis** [comment]
This is a known bug (race condition) in the GOAL debugger itself that has been fixed in the development version of the plug-in; you could update to that (but on your own risk). We don't want to release a new plug-in before the deadline of the individual assignment; we will not use the debugger for our evaluations.

We'll probably make an announcement about this issue in the MAS projecg ASAP. I'll close this issue.
